-- Active: 1666901497263@@127.0.0.1@3306@signup
CREATE DATABASE Signup;
CREATE TABLE Users(Serial_number INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(50) NOT NULL,
Passwords VARCHAR(50) NOT NULL, 
Phone VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL
);
DESC Users;

DROP TABLE Users;
SELECT * FROM Users;